### ISSUE TITLE
Misusage of Tag - Project 2

### ISSUE THREAD

**Issue by JosChavz** [termosa/frontloops#1]
Howdy,

So I know it's not that important especially when you're just practicing styling, but I looked into your code and I found that `payment_method-checkmark` is within an 'i' tag which is told to be, "indicate a technical term, a phrase from another language, a thought, or a ship name, etc.". 

Semantically-wise, I think it would be more of a span tag. Just a heads up!

I really like your code though! It's clean and readable! Great work!

**Comment by termosa** [comment]
Thanks for review @JosChavz !
